Tests for softmax function that accepts infinite gain.

In [1]:
import numpy as np
from ntwk import gsoftmax

In [2]:
z = np.array([
    [0, 1, -1],
    [-5, -5, -5],
    [1, 1, 1],
    [0, 10, 0],
    [100, 0, 100.],
])

for g in [1, 2, -2, 10000, np.inf, -10000, -np.inf]:
    print(f'g = {g}:')
    for z_row, soft_row in zip(z, gsoftmax(z, g)):
        print(f'{z_row} -> {soft_row}')
    print()

g = 1:
[ 0.  1. -1.] -> [0.24472847 0.66524096 0.09003057]
[-5. -5. -5.] -> [0.33333333 0.33333333 0.33333333]
[1. 1. 1.] -> [0.33333333 0.33333333 0.33333333]
[ 0. 10.  0.] -> [4.53958078e-05 9.99909208e-01 4.53958078e-05]
[100.   0. 100.] -> [5.00000000e-01 1.86003799e-44 5.00000000e-01]

g = 2:
[ 0.  1. -1.] -> [0.11731043 0.86681333 0.01587624]
[-5. -5. -5.] -> [0.33333333 0.33333333 0.33333333]
[1. 1. 1.] -> [0.33333333 0.33333333 0.33333333]
[ 0. 10.  0.] -> [2.06115361e-09 9.99999996e-01 2.06115361e-09]
[100.   0. 100.] -> [5.00000000e-01 6.91948263e-88 5.00000000e-01]

g = -2:
[ 0.  1. -1.] -> [0.11731043 0.01587624 0.86681333]
[-5. -5. -5.] -> [0.33333333 0.33333333 0.33333333]
[1. 1. 1.] -> [0.33333333 0.33333333 0.33333333]
[ 0. 10.  0.] -> [4.99999999e-01 1.03057681e-09 4.99999999e-01]
[100.   0. 100.] -> [1.38389653e-87 1.00000000e+00 1.38389653e-87]

g = 10000:
[ 0.  1. -1.] -> [0. 1. 0.]
[-5. -5. -5.] -> [0.33333333 0.33333333 0.33333333]
[1. 1. 1.] -> [0.33333333 0.3333